### ISSUE TITLE
Future Proof?

### ISSUE THREAD

**Issue by alexanderjoe** [MineTheCube/MojangAPI#11]
`In mojang-api.class.php line 178:`
``` The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence```

**Comment by MineTheCube** [comment]
Hi!
It is now (finally) fixed:
- https://github.com/MineTheCube/MojangAPI/commit/b1c18b910075920065ad1c662eb000ea51176c9f

Thanks!
