### ISSUE TITLE
Unrelated Issue

### ISSUE THREAD

**Issue by cashtillo** [MineTheCube/MojangAPI#14]
Hi,

Can I buy your minecraft account? I've used mtc as my name for the longest time and would pay a pretty penny to have your account. If you want to discuss the details please contact me at cstempho@live.com or on Discord: mtc#6767

Thank you.

**Comment by MineTheCube** [comment]
Hello,

I understand your demand, sadly I'll keep my username as it is, I'm not selling it even for a grand.
I hope you'll find another that suits you!

Have a good day.
