### ISSUE TITLE
could you please grant a permissive license to this?

### ISSUE THREAD

**Issue by KisaragiEffective** [MineTheCube/MojangAPI#15]
It'd be great if this can be used under FLOSS license (e.g. MIT or Apache 2.0).

**Comment by domino-1** [comment]
Same, this class would be perfect for a project I'm working on if it had any sort of license allowing its use.

**Comment by MineTheCube** [comment]
it's done guys :)

https://github.com/MineTheCube/MojangAPI/blob/master/LICENSE

**Comment by KisaragiEffective** [comment]
@MineTheCube Great, much appreciated :)
Thank you for adding it!

**Comment by domino-1** [comment]
Thank you!
