### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mouro001** [MineTheCube/MojangAPI#3]
Using Apache 2.4.17, PHP 5.6.15
I'm receiving this:
![screen](http://i.imgur.com/lC9bwY1.png)
While using the example.

**Comment by mouro001** [comment]
Sorry missend the issue:
Using Apache 2.4.17, PHP 5.6.15
Im recieving this: http://i.imgur.com/lC9bwY1.png

**Comment by MineTheCube** [comment]
It seems that it can't reach Mojang servers. It may be a SSL issue, please can you run the following script and copy or screen what outputs ?

```php
<?php

error_reporting(E_ALL);
ini_set('display_errors', true);

var_dump(file_get_contents('https://api.mojang.com/users/profiles/minecraft/MTC'));
```

**Comment by mouro001** [comment]
That worked:
string(54) "{"id":"e9464e86daf14414900b2b08e8710459","name":"MTC"}"

**Comment by MineTheCube** [comment]
But example still doesn't work ?

If not, put this at the very start of the script:
```php
error_reporting(E_ALL);
ini_set('display_errors', true);
```

**Comment by mouro001** [comment]
Getting the same error, no extra info

**Comment by MineTheCube** [comment]
Maybe a cURL error, try this please:
```php
<?php

error_reporting(E_ALL);
ini_set('display_errors', true);

$url = 'https://api.mojang.com/users/profiles/minecraft/MTC';

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5); 
curl_setopt($ch, CURLOPT_TIMEOUT, 5);

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);

$output = curl_exec($ch);
var_dump($output);

var_dump(curl_error($ch), curl_errno($ch));

curl_close($ch);
```

**Comment by mouro001** [comment]
That one is new: 
`bool(false) string(63) "SSL certificate problem: unable to get local issuer certificate" int(60)`

**Comment by MineTheCube** [comment]
It basically means that your cURL installation lacks a SSL certificate.
Try this solution here: http://stackoverflow.com/a/21114601

**Comment by mouro001** [comment]
It works now. Thanks.
