### ISSUE TITLE
The Mojang authentication system does not work.

### ISSUE THREAD

**Issue by ygnakio** [MineTheCube/MojangAPI#4]
In the code I write my data from my account Mojang:
 // Require API
require 'mojang-api.class.php';
$result = MojangAPI::authenticate('my@mail.com', 'mypassword');

if ($result) {
    echo 'Welcome ' . $result['name'] . ', your UUID is: ' . $result['id'];
} else {
    echo 'Sorry, authentication failed.. :(';
} 

And the result shows the **error message**. (Here I deleted my personal data for anyone to see, but in the code I wrote it correctly)

**Comment by MineTheCube** [comment]
I just ran your script with my credentials:
`Welcome MTC, your UUID is: e9464e86daf14414900b2b08e8710459`

Firstly, ensure to put the correct email/password. Try to copy paste what you have in your script in Minecraft launcher and try to login.

Secondly, if you don't have cURL extension enabled, it will not work. Test this:
```php
echo 'This is required to be true: ';
var_dump(function_exists('curl_init') and extension_loaded('curl'));
```

And finally if you try several times in a short period of time, Mojang will automatically deny every further requests even if credentials are correct.
