### ISSUE TITLE
Erreur lors de l'utilisation de curl

### ISSUE THREAD

**Issue by luluxe** [MineTheCube/MojangAPI#6]
A priori vous êtes français moi aussi, ca sera plus simple :) C'est dommage je suis allé sur votre serveur vous n'y étiez pas :(
Bref j'ai trouver un script de test que vous avez partagé dans une autre issue, et j'ai un problème un peu différent :s

```
<?php

error_reporting(E_ALL);
ini_set('display_errors', true);

$url = 'https://api.mojang.com/users/profiles/minecraft/MTC';

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5); 
curl_setopt($ch, CURLOPT_TIMEOUT, 5);

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);

$output = curl_exec($ch);
var_dump($output);

var_dump(curl_error($ch), curl_errno($ch));

curl_close($ch);
```

Le script retourne tout çà :

```
string(555) "
ERROR
The request could not be satisfied.
Request blocked. 
Generated by cloudfront (CloudFront)
Request ID: CjhzWljAre53I1sRh6vNcl92Axbjfi8droxGU_D8qXgzzyuQBTw_eA==
" string(0) "" int(0)
```

J'héberge moi même le site web sur un serveur dedié.
Il tourne sur Debian 8.
J'ai installer l’extension php5-curl.

Sa fait une bonne journée que je cherche un moyen pour résoudre ce problème mais rien a faire.
J'ai essayé un file_get_contents(); qui du-coup marche très bien en local, mais sur le site rien a faire çà ne marche pas. Puis plein d'autres petites solutions sur différents forum, vous m’enlèverez une épine du pied si vous me trouvez le problème ;)

Cordialement,
DURAND LUCAS.

**Comment by MineTheCube** [comment]
À mon avis, ton IP et/où hébergeur est blacklisté de CloudFront ou de l'API Mojang, ou quelque chose du genre.. Est ce que t'as réussi à trouver le pb depuis ?

**Comment by luluxe** [comment]
Hello, je n'ai toujours pas trouver le problème, je suis sur un serveur dedié OVH, et c'est moi qui est mis tout en place donc le serveur apache. Je pense que logiquement je ne doit pas être blacklisté, tu n'aurais pas un script qui permettrait de tester pour trouver le problème ?

**Comment by MineTheCube** [comment]
```php
<?php
var_dump(file_get_contents('https://api.mojang.com/users/profiles/minecraft/MTC'));
var_dump(file_get_contents('https://status.mojang.com/check'));
```

Devrait donner:
```
string(54) "{"id":"e9464e86daf14414900b2b08e8710459","name":"MTC"}"
string(308) "[{"minecraft.net":"green"},{"session.minecraft.net":"green"},{"account.mojang.com":"green"},{"auth.mojang.com":"green"},{"skins.minecraft.net":"green"},{"authserver.mojang.com":"green"},{"sessionserver.mojang.com":"green"},{"api.mojang.com":"green"},{"textures.minecraft.net":"green"},{"mojang.com":"green"}]"
```

Test et dis moi ce que t'as.

Ah, et essaie ça avec l'IP de ton dédié:
https://www.whatismyip.com/blacklist-check/?iref=my-ip-info

**Comment by luluxe** [comment]
Hello, sorry de t'avoir dérangé c'est bizarre quelques jours après le problème sur mon serveur principale j'ai donc testé ton script il n'y a eu 0 soucis. Ensuite j'ai testé sur mon serveur test et comme le premier serveur au début sa ne marchait pas, mais au bout de quelques jours çà marche et depuis les deux serveurs çà marche nickel sans soucis.
Donc a mon avis Mojang block au début pour s'assurer que c'est une source fiable et ensuite le déblock. Donc je suis désolé et encore merci de ton aide.

Cordialement,
DURAND Lucas.
