### ISSUE TITLE
Can't get server players.

### ISSUE THREAD

**Issue by WebWorm3** [MineTheCube/MojangAPI#7]
Hey! I am trying to get hypixel's players online on my site but it always says that this server is offline :(
`<?php
				    require 'MojangAPI/mojang-api.class.php';  
				        $query = MojangAPI::query('eu.hypixel.net', 25565);
                                            if ($query) echo '<a href="#" style="color: green;">Hypixel online' . $query['players'] . '/' . $query['maxplayers']. '</a>';
                                            else echo '<a href="#" style="color: red;">Hypixel is offline.</a>'
?>`
P.S. your example won't work too.

**Comment by MineTheCube** [comment]
Because Hypixel doesn't seem to allow query protocol. So you just have to use `ping` method like this: `MojangAPI::ping('eu.hypixel.net')` to make it work!

**Comment by WebWorm3** [comment]
Nah, I I just used other api. Your’s not work.

**Comment by MineTheCube** [comment]
The following code:
```php
<?php
require 'MojangAPI/mojang-api.class.php';
$query = MojangAPI::ping('mc.hypixel.net', 25565);
if ($query) echo '<a href="#" style="color: green;">Hypixel online ' . $query['players']['online'] . '/' . $query['players']['max']. '</a>';
else echo '<a href="#" style="color: red;">Hypixel is offline.</a>';
```

Does output:
`<a href="#" style="color: green;">Hypixel online 38140/62000</a>`.

So yes, it does work :)

**Comment by WebWorm3** [comment]
hmmm ok... But I am already using this one [*click*](https://github.com/xPaw/PHP-Minecraft-Query) :p

**Comment by MineTheCube** [comment]
This is exactly the same implementation, but ok as you want
